# Site settings
title: Ecosistema 
email: contato@labrio.org
description: > # this means to ignore newlines until "baseurl:"
  ECOSISTEMA es una unidad natural que comprende diferentes elemento 
  que interactúan y se relacionan entre sí, formando un sistema en 
  constante renovación, innovación y crecimiento.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://latamlabs.cc" # the base hostname & protocol for your site
twitter_username: _labrio 
github_username:  LAB-Rio

# Build settings
markdown: kramdown
